services:

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:8080"
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - user-db

  user-db:
    image: postgres:18-alpine
    container_name: user-db
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5001:8080"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5002:8080"
    networks:
      - backend
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - PAYMENT_SERVICE_URL=http://payment-service:8080

  mini-app-service:
    build: ./mini-app-service
    container_name: mini-app-service
    ports:
      - "5003:8080"
    networks:
      - backend
      - mini-apps

volumes:
  user-db-data:

networks:
  backend:
    driver: bridge
  mini-apps:
    driver: bridge
    name: allesnl-mini-app_network